results_dir: "out/logs"
seed: 0
algorithm: "sac"  
env_str: "hopper_fixed_hurdles"  
horizon: 1000
gamma: 0.99
n_features: 128 
learning_rate: # TODO tune this parameter range(0.0005 ~ 0.001)
lr_alpha: 0.0008         
batch_size: 256
initial_replay_size: 2000 
max_replay_size: 200000
tau: 0.005
warmup_transitions: 1000
n_epochs: 50 
n_steps_training_per_epoch: 20000
n_steps_per_fit: 1
n_episodes_test_per_epoch: 5
