results_dir: "out/logs"
seed: 0 
algorithm: "td3"  
env_str: "hopper_fixed_hurdles"  
horizon: 1000
gamma: 0.99
n_features: 128 
batch_size: 256
learning_rate: 0.001   
policy_sigma: # TODO: tune this parameter range(0.0001 ~ 0.01)
initial_replay_size: 2000
max_replay_size: 200000
tau: 0.005
n_epochs: 60
n_steps_training_per_epoch: 20000
n_steps_per_fit: 1
n_episodes_test_per_epoch: 5
